[application]

# dioxus project name
name = "diogen"

# default platfrom
# you can also use `dioxus serve/build --platform XXX` to use other platform
# value: web | desktop
default_platform = "web"

# Web `build` & `serve` dist path
out_dir = "dist"

# resource (static) file folder
public_dir = "public"

[web.app]

# HTML title tag content
title = "diogen | ⛺"

[web.watcher]

watch_path = [
    "src",
    "public"
]

# include `assets` in web platform
[web.resource]

# CSS style file
style = [
    # "https://cdn.bootcdn.net/ajax/libs/pure/2.0.6/pure.min.css",
    "./assets/bulma.min.css"
]

# Javascript code file
script = [
    "./app.js"
]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []